#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler'
require 'bundler/setup'

require 'telefactor/repo_management'

puts Telefactor::RepoManagement
puts Telefactor::RepoManagement::Secrets.secrets
puts Telefactor::RepoManagement.octokit_client
