#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler'
require 'bundler/setup'

require 'telefactor/repo_management'

manager = Telefactor::RepoManagement::Manager.new
puts manager.telefactor_repos.map(&:name)
