#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler'
require 'bundler/setup'

require 'git'
require 'shell'

require 'telefactor/repo_management'
include Telefactor::RepoManagement

THIS_FILE = Pathname(__FILE__).expand_path
TELEFACTOR_ROOT = begin
    dir = THIS_FILE.parent
    while dir.exist? && !(dir/'.git').exist? do
      puts dir
      dir = dir.parent
    end
    dir
  end

puts('TELEFACTOR_ROOT', TELEFACTOR_ROOT)

sh = Shell.cd(TELEFACTOR_ROOT)
sh.pushdir(TELEFACTOR_ROOT / 'games' / '01-connery' / 'repos')
puts(sh.pwd)
telefactor_git = Git.open(TELEFACTOR_ROOT)



# game = Shawn.new

# latest_repo = game.latest_repo
# puts('latest', latest_repo)

# if latest_repo.role == Shawn::Roles::EXAMINER
# end
