#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler'
require 'bundler/setup'

require 'tty-prompt'

require 'telefactor/repo_management'

prompt = TTY::Prompt.new
manager = Telefactor::RepoManagement::Manager.new

ap(
  'user name' => manager.user.name,
  'telefactor repo names' => manager.fam_repos.map(&:name)
)

fam_repos.each do |repo|
  next if prompt.no?("Make #{repo.name} public?")

  response =
    begin
      client.edit_repository(
        {
          owner: manager.user.login,
          repo: repo.name,
        },
        private: false
      )
    rescue StandardError => e
      ap(backtrace: e.backtrace)
      require 'pry'; binding.pry

      'failed response'
    end
  ap(response: response)
end
