#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler'
require 'bundler/setup'

require 'tty-prompt'

require 'telefactor/repo_management'

prompt = TTY::Prompt.new
fam = Telefactor::RepoManagement::Fam.new

ap(
  'user name' => fam.user.name,
  'telefactor repo names' => fam.repos.map(&:name)
)

fam.repos.each do |repo|
  next if prompt.no?("Make #{repo.name} public?")

  response =
    begin
      fam.client.edit_repository(
        {
          owner: fam.user.login,
          repo: repo.name,
        },
        private: false
      )
    rescue StandardError => e
      ap(backtrace: e.backtrace)
      require 'pry'; binding.pry

      'failed response'
    end
  ap(response: response)
end
